# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_presenter}
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Golick", "Daniel Haran", "Igor Galeta"]
  s.date = %q{2010-08-11}
  s.description = %q{ActivePresenter is the presenter library you already know! (...if you know ActiveRecord)}
  s.email = %q{james@giraffesoft.ca}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "lib/active_presenter.rb",
     "lib/active_presenter/base.rb",
     "lib/active_presenter/version.rb"
  ]
  s.homepage = %q{git://github.com/galetahub/freeberry.git}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{active_presenter}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{ActivePresenter is the presenter library}
  s.test_files = [
    "test/base_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

